background_opacity          0.6
cursor_trail                2
window_padding_width        25

include themes/noctalia.conf
map ctrl+shift+a launch --type=clipboard --stdin-source=@screen_scrollback


#added by me 
font_family JetBrainsMono Nerd Font
