foreground            #dde4e4
background            #0e1415
selection_foreground  #003739
selection_background  #f1ffff
url_color             #fffaff
cursor                #f1ffff
cursor_text_color     #003739

color0   #0e1415
color1   #ffb4ab
color2   #f1ffff
color3   #fffaff
color4   #f1ffff
color5   #fffaff
color6   #ffdd65
color7   #dde4e4

color8   #859394
color9   #ffb4ab
color10  #f1ffff
color11  #fffaff
color12  #f1ffff
color13  #fffaff
color14  #ffdd65
color15  #dde4e4

tab_bar_background              #0e1415
tab_bar_margin_color            #0e1415
active_tab_foreground           #003739
active_tab_background           #f1ffff
inactive_tab_foreground         #bbc9ca
inactive_tab_background         #0e1415
