[Audio]
Volume=25

[General]
FileDialogLastLocation=file:///home/yooo/Videos/p
LastPlayedFile=file:///run/media/yooo/47fe6a9e-4560-4060-a3ec-543a5eb12601/vaultusbm/p/Chloe Cherry - Loving It - BlackedRaw %5Bchloe-cherry-loving-it-blackedraw%5D.mp4
